platform: x64

image:
  - Visual Studio 2017

branches:
  only:
    - master

install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env
  - go get -u github.com/jteeuwen/go-bindata/...
  - go get -v

build_script:
  - go generate -v ./...
  - go build -i -v
