"""Programming Submissions updates

Revision ID: 4345ec5745ac
Revises: 64a5547e521c
Create Date: 2016-07-24 07:05:57.011880

"""

# revision identifiers, used by Alembic.
revision = '4345ec5745ac'
down_revision = '64a5547e521c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programming_submissions', sa.Column('creation_time', sa.Integer(), nullable=True))
    op.add_column('programming_submissions', sa.Column('execution_time', sa.Float(), nullable=True))
    op.add_column('programming_submissions', sa.Column('jid', sa.Integer(), nullable=True))
    op.add_column('programming_submissions', sa.Column('language', sa.String(length=32), nullable=True))
    op.add_column('programming_submissions', sa.Column('uid', sa.Integer(), nullable=True))
    op.add_column('programming_submissions', sa.Column('verdict', sa.String(length=256), nullable=True))
    op.drop_column('programming_submissions', 'date')
    op.drop_column('programming_submissions', 'submission_path')
    op.drop_column('programming_submissions', 'message')
    op.drop_column('programming_submissions', 'log')
    op.drop_column('programming_submissions', 'number')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programming_submissions', sa.Column('number', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('programming_submissions', sa.Column('log', mysql.TEXT(collation=u'utf8_unicode_ci'), nullable=True))
    op.add_column('programming_submissions', sa.Column('message', mysql.TEXT(collation=u'utf8_unicode_ci'), nullable=True))
    op.add_column('programming_submissions', sa.Column('submission_path', mysql.TEXT(collation=u'utf8_unicode_ci'), nullable=True))
    op.add_column('programming_submissions', sa.Column('date', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('programming_submissions', 'verdict')
    op.drop_column('programming_submissions', 'uid')
    op.drop_column('programming_submissions', 'language')
    op.drop_column('programming_submissions', 'jid')
    op.drop_column('programming_submissions', 'execution_time')
    op.drop_column('programming_submissions', 'creation_time')
    ### end Alembic commands ###
